// Regenerates src/assets.ts from the source images in assets-src/.
// Each scene image is re-encoded to WebP and inlined as a base64 data URI, so
// the package ships with zero image files for consumers to copy into public/.
//
//   node scripts/convert-assets.mjs
//
// To add a new city: drop a <name>-day.png (transparent) and optional
// <name>-night.jpg into assets-src/, add it to SCENES below, then register it
// in src/scenes.ts.
import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "..", "assets-src");
const OUT = join(__dirname, "..", "src", "assets.ts");

// Cap width — the mosaic only ever samples at CSS width (~1600px on large
// screens), so there's no point shipping anything larger.
const MAX_W = 1600;

const SCENES = [
  { key: "SF_DAY", file: "sf-day.png", quality: 82 },
  { key: "SF_NIGHT", file: "sf-night.jpg", quality: 78 },
  // Archived for now — source stays in assets-src/, re-add to ship it again:
  // { key: "PAINTED_LADIES", file: "painted-ladies.png", quality: 82 },
];

async function toWebpDataUri(file, quality) {
  const img = sharp(join(SRC, file));
  const meta = await img.metadata();
  const width = Math.min(meta.width, MAX_W);
  const buf = await img
    .resize({ width, withoutEnlargement: true })
    .webp({ quality, alphaQuality: 90, effort: 6 })
    .toBuffer();
  return {
    dataUri: `data:image/webp;base64,${buf.toString("base64")}`,
    bytes: buf.length,
    width,
    srcWidth: meta.width,
  };
}

let total = 0;
const entries = [];
for (const scene of SCENES) {
  const { dataUri, bytes, width, srcWidth } = await toWebpDataUri(
    scene.file,
    scene.quality
  );
  total += dataUri.length;
  console.log(
    `${scene.key.padEnd(16)} ${String(srcWidth).padStart(4)}px → ${width}px  ` +
      `${(bytes / 1024).toFixed(1)}KB webp  ${(dataUri.length / 1024).toFixed(1)}KB b64`
  );
  entries.push({ key: scene.key, dataUri });
}
console.log(`\nTotal inlined payload: ${(total / 1024).toFixed(1)}KB`);

const header = `// AUTO-GENERATED by scripts/convert-assets.mjs — do not edit by hand.
// Skyline scene images, inlined as WebP data URIs so the package works in any
// bundler with zero image files to copy into public/.
/* eslint-disable */
`;
// Annotate as `: string` so tsup doesn't inline the whole base64 blob into the
// generated .d.ts as a literal string type.
const body = entries
  .map((e) => `export const ${e.key}_DATA_URI: string =\n  "${e.dataUri}";`)
  .join("\n\n");
const compat = `
// Back-compat aliases for the names exported by 0.3.x.
export const DAY_SKYLINE_DATA_URI = SF_DAY_DATA_URI;
export const NIGHT_SKYLINE_DATA_URI = SF_NIGHT_DATA_URI;
`;

writeFileSync(OUT, `${header}\n${body}\n${compat}`);
console.log(`\nWrote ${OUT}`);
